# Generated by Django 4.2.7 on 2023-11-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppetizerItem',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('picture', models.ImageField(null=True, upload_to='menu_images')),
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='BeverageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('picture', models.ImageField(null=True, upload_to='menu_images')),
            ],
        ),
        migrations.CreateModel(
            name='DesertItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('picture', models.ImageField(null=True, upload_to='menu_images')),
            ],
        ),
        migrations.CreateModel(
            name='EntreeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('picture', models.ImageField(null=True, upload_to='menu_images')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('picture', models.ImageField(null=True, upload_to='menu_images')),
            ],
        ),
        migrations.CreateModel(
            name='SideItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('picture', models.ImageField(null=True, upload_to='menu_images')),
            ],
        ),
    ]
