# Generated by Django 4.2.7 on 2023-11-13 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoItem',
            new_name='MenuItem',
        ),
    ]
