# Generated by Django 4.2.7 on 2023-11-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appetizeritem',
            name='picture',
            field=models.ImageField(default='', upload_to='menu_images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beverageitem',
            name='picture',
            field=models.ImageField(default='', upload_to='menu_images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='desertitem',
            name='picture',
            field=models.ImageField(default='', upload_to='menu_images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entreeitem',
            name='picture',
            field=models.ImageField(default='', upload_to='menu_images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='picture',
            field=models.ImageField(default='', upload_to='menu_images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sideitem',
            name='picture',
            field=models.ImageField(default='', upload_to='menu_images'),
            preserve_default=False,
        ),
    ]
