# Generated by Django 4.2.7 on 2023-11-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_todoitem_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
