# Generated by Django 4.2.7 on 2023-11-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_menuitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='picture',
            field=models.ImageField(null=True, upload_to='menu_images'),
        ),
    ]
