# Generated by Django 4.2.7 on 2023-11-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_appetizeritem_desertitem_drinkitem_entreeitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appetizeritem',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='desertitem',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='drinkitem',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='entreeitem',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='completed',
        ),
        migrations.AlterField(
            model_name='appetizeritem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='desertitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='drinkitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='entreeitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
