# Generated by Django 4.2.7 on 2023-11-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_entreeitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreeitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
